name: Deploy Game

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup cache
        uses: actions/cache@v6
        with:
          path: "./build/release/_deps"
          key: deps-${{ runner.os }}-emsdk-6.0.10

      - uses: mymindstorm/setup-emsdk@v16
        with:
          version: 6.0.10
          actions-cache-folder: "emsdk-cache"

      - name: Download ports
        run: |
          embuilder build harfbuzz

      - name: Configure
        run: emcmake cmake --preset release

      - name: Build
        run: cmake --build --preset release

      - uses: actions/upload-pages-artifact@v5
        with:
          path: ./build/release/target/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
